### PR TITLE
[fix] navigation-component

### PR DESCRIPTION
**Pull request by abhij1607**
- improved responsiveness for navigation

### CODE REVIEW

**Review by shivampandey0 — COMMENTED** [review]
Clean code with easy-to-understand class names.
Good to merge

**Review by Hamdrive — COMMENTED** [review]
Good work done, good use of `flex-basis` to dynamicly size your navigation
Can be merged!

**Review by stutisk — APPROVED** [review]
Code looks clean to me, can go frwd with merging it

**Review by Jia-A — COMMENTED** [review]
Can be merged, code looks good.

**Pull request merged**
