### PR TITLE
Feat- slider

### PR DESCRIPTION
**Pull request by abhij1607**
image

### please review only slider.html, the rest are carried over from the last branch and have already been raised for PR.

- this PR is for the slider component with tick marks, labels are also included but not supported by all browsers right now

### CODE REVIEW

**Review by prachi-sahani — COMMENTED** [review]
clean code and good to merge

Suggestion - try keeping files/code related to PR only

**Review by Hamdrive — COMMENTED** [review]
Good use of css custom utility class, and implementation of rating logic without using Javascript
Overall rating component is good

**Review by shivampandey0 — APPROVED** [review]
Good work! A self-explanatory naming scheme with the use of CSS variables.
Good to merge

**Comment by abhij1607** [comment]
Got good reviews. So, merging the PR

**Pull request merged**
